# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [15]:
data = pd.read_csv('Data.csv')

# iloc takes the indexes of both the rows and columns, the rows and columns are
# separated by ','
X = data.iloc[:, :-1].values # features, all the columns except the last one
Y = data.iloc[:, -1].values # dependent variables, only the last column

In [16]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [14]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [17]:
# The SimpleImputer class is used for handling missing values in a dataset
from sklearn.impute import SimpleImputer

# creates an instance of SimpleImputer with the missing_values parameter set to 
# np.nan and the strategy parameter set to 'mean'
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# fits the SimpleImputer instance imputer to the columns 1 and 2 
# (indexing starts from 0) of the array X
imputer.fit(X[:, 1:3])
# applies the transformation using the fitted SimpleImputer instance imputer to 
# the columns 1 and 2 (indexing starts from 0) of the array X
X[:, 1:3] = imputer.transform(X[:, 1:3])



In [18]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [19]:
# The ColumnTransformer class is part of scikit-learn and is used for applying 
# different transformations to different columns of a dataset
from sklearn.compose import ColumnTransformer

# The OneHotEncoder class is used for converting categorical features into a 
# one-hot encoded representation. It transforms categorical variables into a 
# binary vector format where each category is represented by a binary feature column
from sklearn.preprocessing import OneHotEncoder

#  creates a ColumnTransformer named ct with a single transformation
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# The code x = np.array(ct.fit_transform(x)) applies the ColumnTransformer 
# transformation specified by ct to the array x, and then converts the 
# transformed result into a NumPy array.
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [21]:
# The LabelEncoder class is used for encoding categorical labels (i.e., target 
# variables or class labels) with numerical values
from sklearn.preprocessing import LabelEncoder

# creates an instance of the LabelEncoder class and assigns it to the variable le
le = LabelEncoder()

# fits the LabelEncoder instance le to the array y and transforms the labels 
# into their encoded numerical representation
Y = le.fit_transform(Y)

In [22]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [23]:
# The train_test_split function is commonly used for splitting a dataset into 
# training and testing subsets
from sklearn.model_selection import train_test_split

# splits the arrays X and Y into training and testing sets using the 
# train_test_split function. The resulting splits are assigned to the 
# variables X_train, X_test, Y_train, and Y_test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1) # The random_state parameter in the train_test_split function is used to set the random seed for the random number generator. By setting the random seed to a specific value, such as 1 in your example, you ensure that the random shuffling and splitting of the data will be reproducible

In [24]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [25]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [26]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [27]:
print(Y_test)

[0 1]


## Feature Scaling

In [28]:
# The StandardScaler class is used for standardizing features by removing the 
# mean and scaling to unit variance
from sklearn.preprocessing import StandardScaler

# creates an StandardScaler object
sc = StandardScaler()

# uses the fit_transform method of a StandardScaler instance to standardize a 
# subset of features in the X_train array
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

# applies the transformation learned from the StandardScaler instance (sc) 
# to standardize a subset of features in the X_test array
X_test[:, 3:] = sc.transform(X_test[:, 3:])


In [29]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [30]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
